version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  exporter:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ../:/opt/node_app/app:delegated
      - ../package.json:/opt/node_app/package.json
      - ../package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
    environment:
      KAFKA_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      PARITY_URL: http://parity.stage.san:30954
      START_BLOCK: "5710092"
      BLOCK_INTERVAL: "50"
      EXPORT_TIMEOUT_MLS: 300000
    ports:
      # port for checking health.
      - "127.0.0.1:3000:3000"
    entrypoint: "/bin/sh"
    command: ["-c", "docker/wait_for_services.sh && npm start"]

volumes:
  notused: