version: '3.4'
services:
  test:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: development
    entrypoint: ["npm", "test"]
    #entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - "../test/contract_mapping/:/opt/app/lib/contract_mapping"
